const SHEET_ID='1W2wjikf5fOYqkaY5Qoal4820Z5WYw2FiIZyU8JNIJZY';
const endpoint=location.protocol==='http:'&&location.hostname==='localhost'?'/__dama_orders':`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&gid=0`;
let allOrders=[];
const money=n=>new Intl.NumberFormat('en-US').format(Math.round(n||0));
function parseGviz(text){return JSON.parse(text.substring(text.indexOf('{'),text.lastIndexOf('}')+1));}
function loadRows(payload){return payload.table.rows.map((r,i)=>{const v=r.c.map(c=>c?.v??'');const j=String(v[6]||'');let items=[];try{items=JSON.parse(j)}catch{};return{id:i,date:v[0],delivered:String(v[1]).toLowerCase()==='true',name:v[2],phone:v[3],wa:v[4],insta:v[5],items,address:v[7],notes:v[8],total:Number(v[9])||0,profit:Number(v[12])||0}}).filter(o=>o.name||o.date||o.total)}
const fallback=[
 {date:'2026-07-28T07:59:55.674Z',delivered:false,name:'Jonathan Labusch',phone:'968504016',insta:'jonnylabusch',items:[{name:'الحرب مو منيحة لصحتك',quantity:2},{name:'السلاح الفلتان، اربطوه',quantity:2},{name:'دبكة',quantity:3},{name:'طوابع - 2',quantity:2},{name:'ليرة',quantity:1},{name:'فناجين',quantity:2}],address:'Pickup',notes:'',total:60000,profit:24000},
 {date:'2026-04-03T14:32:13.218Z',delivered:true,name:'Mohamad Alsaidi',phone:'940109084',insta:'@ Mohamad.Alsaidi',items:[{name:'الحرب مو منيحة لصحتك',quantity:1},{name:'الناطق الرسمي',quantity:1},{name:'معي تلاتمية',quantity:1},{name:'مليت بس مكمل',quantity:1},{name:'طوابع - 1',quantity:1},{name:'طوابع - 2',quantity:1},{name:'فناجين',quantity:1}],address:'التضامن',notes:'',total:50000,profit:20000},
 {date:'2026-03-25T16:47:19.338Z',delivered:false,name:'Aref Alkrez',phone:'931613501',insta:'@aref.alkrez',items:[{name:'الحرب مو منيحة لصحتك',quantity:5},{name:'الناطق الرسمي',quantity:1},{name:'هالضفدع ما حيموت سلق',quantity:3},{name:'فيقي وصحصحي',quantity:4},{name:'بحب سوريا، أحيانا',quantity:8},{name:'Local Merch',quantity:1}],address:'الشعلان بناية بوظة دامر',notes:'',total:350000,profit:140000},
 {date:'2026-03-11T20:58:18.216Z',delivered:false,name:'Aref Alkrez',phone:'931613501',insta:'aref.alkrez',items:[{name:'الحرب مو منيحة لصحتك',quantity:3},{name:'الناطق الرسمي',quantity:3},{name:'دبكة',quantity:2},{name:'طاولة تلفزيون',quantity:2}],address:'الشعلان، شارع ميسلون',notes:'',total:500000,profit:200000},
 {date:'2026-03-09T19:55:18.144Z',delivered:true,name:'Judy Al Hamad',phone:'937226655',insta:'@judyyyyyy2',items:[{name:'الحرب مو منيحة لصحتك',quantity:1},{name:'المقاومة مو جكر',quantity:1},{name:'فيقي وصحصحي',quantity:1},{name:'دبكة',quantity:2}],address:'NA',notes:'',total:30000,profit:12000}
];
async function fetchData(){const button=document.querySelector('#refresh');button.disabled=true;button.textContent='Refreshing…';try{const url=endpoint+(endpoint.includes('?')?'&':'?')+'_='+Date.now();const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error();allOrders=loadRows(parseGviz(await res.text()));document.querySelector('#status').dataset.mode='live'}catch{allOrders=fallback;document.querySelector('#status').dataset.mode='fallback';document.querySelector('#status').textContent='Showing a local snapshot · live sheet unavailable'}render();button.disabled=false;button.textContent='Refresh data'}
function filtered(){const q=document.querySelector('#search').value.toLowerCase(),sf=document.querySelector('#statusFilter').value,from=document.querySelector('#from').value,to=document.querySelector('#to').value;return allOrders.filter(o=>(!q||JSON.stringify(o).toLowerCase().includes(q))&&(sf==='all'||(sf==='delivered'&&o.delivered)||(sf==='open'&&!o.delivered))&&(!from||o.date>=from)&&(!to||o.date<=to+'T23:59:59'))}
function render(){const data=filtered(),revenue=data.reduce((s,o)=>s+o.total,0),profit=data.reduce((s,o)=>s+o.profit,0),units=data.reduce((s,o)=>s+o.items.reduce((a,i)=>a+(Number(i.quantity)||0),0),0);const status=document.querySelector('#status');if(status.dataset.mode==='live')status.textContent=`${allOrders.length} orders · live sheet · refreshed ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`;document.querySelector('#summary').innerHTML=[['Revenue',money(revenue)+' SYP'],['Profit',money(profit)+' SYP'],['Units sold',money(units)],['Average order',money(data.length?revenue/data.length:0)+' SYP']].map(x=>`<div class="metric"><span class="label">${x[0]}</span><span class="value">${x[1]}</span></div>`).join('');renderChart(data);renderProducts(data);document.querySelector('#count').textContent=`${data.length} shown`;document.querySelector('#orders').innerHTML=data.sort((a,b)=>b.date.localeCompare(a.date)).map((o,i)=>`<tr><td>${o.date?new Date(o.date).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—'}</td><td><span class="name">${o.name||'Unnamed'}</span><span class="sub">${o.phone||''} ${o.insta?' · '+o.insta:''}</span></td><td>${o.items.length} lines <span class="sub">${o.items.reduce((s,x)=>s+(x.quantity||0),0)} units</span></td><td>${money(o.total)} <span class="sub">SYP</span></td><td>${money(o.profit)} <span class="sub">SYP</span></td><td><span class="pill ${o.delivered?'done':''}">${o.delivered?'Delivered':'Open'}</span></td><td><span class="link" data-detail="${i}">View</span></td></tr><tr class="details" id="detail-${i}"><td colspan="7"><strong>${o.items.map(x=>`${x.name} ×${x.quantity}`).join(' · ')||'No item details'}</strong><br>${o.address||'No address'}${o.notes?' · '+o.notes:''}</td></tr>`).join('');document.querySelectorAll('[data-detail]').forEach(el=>el.onclick=()=>document.querySelector('#detail-'+el.dataset.detail).classList.toggle('open'))}
function renderChart(data){const groups={};data.forEach(o=>{const k=o.date?.slice(0,7)||'Unknown';groups[k]??={total:0,profit:0};groups[k].total+=o.total;groups[k].profit+=o.profit});const vals=Object.entries(groups).slice(-12),max=Math.max(1,...vals.map(([,v])=>v.total));document.querySelector('#chart').innerHTML=vals.map(([k,v])=>`<div class="bar-wrap"><div class="bar" style="height:${v.total/max*100}%"></div><div class="bar profit" style="height:${Math.max(2,v.profit/max*100)}%"></div><span class="bar-label">${k}</span></div>`).join('')+`<div class="chart-legend"><span style="color:var(--accent)">● revenue</span> &nbsp; <span style="color:var(--green)">● profit</span></div>`}
function renderProducts(data){const map={};data.forEach(o=>o.items.forEach(i=>{map[i.name]??=0;map[i.name]+=Number(i.quantity)||0}));const top=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8),max=top[0]?.[1]||1;document.querySelector('#products').innerHTML=top.length?top.map(([n,v])=>`<div class="product"><span>${n}</span><small>${v} units</small><div class="track"><div class="fill" style="width:${v/max*100}%"></div></div></div>`).join(''):'<span class="muted">No product data in this view.</span>'}
['search','statusFilter','from','to'].forEach(id=>document.querySelector('#'+id).addEventListener('input',render));document.querySelector('#refresh').onclick=()=>fetchData();document.querySelector('#export').onclick=()=>{const rows=filtered().map(o=>[o.date,o.name,o.phone,o.total,o.profit,o.delivered?'Delivered':'Open',o.items.map(i=>`${i.name} x${i.quantity}`).join('; ')]);const csv=[['Date','Customer','Phone','Total','Profit','Status','Items'],...rows].map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='dama-orders.csv';a.click()};fetchData().catch(e=>document.querySelector('#status').textContent=e.message);
